/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CareersCareerIdRouteImport } from './routes/careers.$careerId'
import { Route as ResultsSimulationIdRouteImport } from './routes/results.$simulationId'
import { Route as SimulationsIndexRouteImport } from './routes/simulations.index'
import { Route as SimulationsSimulationIdRouteImport } from './routes/simulations.$simulationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersCareerIdRoute = CareersCareerIdRouteImport.update({
  id: '/careers/$careerId',
  path: '/careers/$careerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSimulationIdRoute = ResultsSimulationIdRouteImport.update({
  id: '/results/$simulationId',
  path: '/results/$simulationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIndexRoute = SimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsSimulationIdRoute = SimulationsSimulationIdRouteImport.update({
  id: '/simulations/$simulationId',
  path: '/simulations/$simulationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/careers/$careerId': typeof CareersCareerIdRoute
  '/results/$simulationId': typeof ResultsSimulationIdRoute
  '/simulations/$simulationId': typeof SimulationsSimulationIdRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/careers/$careerId': typeof CareersCareerIdRoute
  '/results/$simulationId': typeof ResultsSimulationIdRoute
  '/simulations/$simulationId': typeof SimulationsSimulationIdRoute
  '/simulations': typeof SimulationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assessment': typeof AssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/careers/$careerId': typeof CareersCareerIdRoute
  '/results/$simulationId': typeof ResultsSimulationIdRoute
  '/simulations/$simulationId': typeof SimulationsSimulationIdRoute
  '/simulations/': typeof SimulationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/careers/$careerId'
    | '/results/$simulationId'
    | '/simulations/$simulationId'
    | '/simulations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/careers/$careerId'
    | '/results/$simulationId'
    | '/simulations/$simulationId'
    | '/simulations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessment'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/careers/$careerId'
    | '/results/$simulationId'
    | '/simulations/$simulationId'
    | '/simulations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssessmentRoute: typeof AssessmentRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  CareersCareerIdRoute: typeof CareersCareerIdRoute
  ResultsSimulationIdRoute: typeof ResultsSimulationIdRoute
  SimulationsSimulationIdRoute: typeof SimulationsSimulationIdRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$careerId': {
      id: '/careers/$careerId'
      path: '/careers/$careerId'
      fullPath: '/careers/$careerId'
      preLoaderRoute: typeof CareersCareerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$simulationId': {
      id: '/results/$simulationId'
      path: '/results/$simulationId'
      fullPath: '/results/$simulationId'
      preLoaderRoute: typeof ResultsSimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof SimulationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$simulationId': {
      id: '/simulations/$simulationId'
      path: '/simulations/$simulationId'
      fullPath: '/simulations/$simulationId'
      preLoaderRoute: typeof SimulationsSimulationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssessmentRoute: AssessmentRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  CareersCareerIdRoute: CareersCareerIdRoute,
  ResultsSimulationIdRoute: ResultsSimulationIdRoute,
  SimulationsSimulationIdRoute: SimulationsSimulationIdRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
